import type { UserProfile, Post, FoodCircle, Comment, Reaction, CircleMembership } from '../types';

const NOW = Date.now();
const HOUR = 3600_000;

export const SEED_PROFILES: UserProfile[] = [
  {
    id: 'user-demo',
    username: 'stomachstanford',
    email: 'demo@stanford.edu',
    avatar_url: 'https://api.dicebear.com/7.x/notionists/svg?seed=stomachstanford',
    bio: 'Always hunting for the best bites around campus 🍜',
    food_personality: 'Adventurous Night Owl 🌙🌶️',
    created_at: new Date(NOW - 30 * 24 * HOUR).toISOString(),
  },
  {
    id: 'user-2',
    username: 'foodiefrosh',
    email: 'frosh@stanford.edu',
    avatar_url: 'https://api.dicebear.com/7.x/notionists/svg?seed=foodiefrosh',
    bio: 'First year discovering all the hidden food spots 🥟',
    food_personality: 'Curious Explorer 🗺️',
    created_at: new Date(NOW - 60 * 24 * HOUR).toISOString(),
  },
  {
    id: 'user-3',
    username: 'snacksensei',
    email: 'snacks@stanford.edu',
    avatar_url: 'https://api.dicebear.com/7.x/notionists/svg?seed=snacksensei',
    bio: 'Free food radar: always on 🔍',
    food_personality: 'Free Food Pro 🧋',
    created_at: new Date(NOW - 90 * 24 * HOUR).toISOString(),
  },
];

export const SEED_POSTS: Post[] = [
  {
    id: 'post-1',
    author_id: 'user-3',
    type: 'free_food',
    title: 'Free boba & snacks at Huang rn!!',
    description: 'CS club is giving out free boba and assorted snacks in the Huang basement lounge. Taro and matcha flavors available. Come fast — goes until 5pm or while supplies last! 🧋',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=480&fit=crop',
    location_name: 'Huang Basement',
    latitude: 37.4276,
    longitude: -122.1730,
    cuisine_tags: ['boba', 'snacks'],
    dietary_tags: ['vegan'],
    is_free_food: true,
    expires_at: new Date(NOW + 2 * HOUR).toISOString(),
    circle_id: 'circle-free-food',
    created_at: new Date(NOW - 25 * 60000).toISOString(),
    updated_at: new Date(NOW - 25 * 60000).toISOString(),
    like_count: 34,
    still_there_count: 12,
    comment_count: 8,
    mock_rating: undefined,
    mock_is_open: true,
  },
  {
    id: 'post-2',
    author_id: 'user-2',
    type: 'free_food',
    title: 'Leftover pizza in Arrillaga dining',
    description: 'There\'s a whole stack of leftover pizza slices outside Arrillaga — looks like they had an event. Cheese and veggie options. First come first served!',
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=480&fit=crop',
    location_name: 'Arrillaga',
    latitude: 37.4243,
    longitude: -122.1685,
    cuisine_tags: ['pizza'],
    dietary_tags: ['vegetarian'],
    is_free_food: true,
    expires_at: new Date(NOW + 45 * 60000).toISOString(),
    circle_id: 'circle-free-food',
    created_at: new Date(NOW - 15 * 60000).toISOString(),
    updated_at: new Date(NOW - 15 * 60000).toISOString(),
    like_count: 21,
    still_there_count: 5,
    comment_count: 3,
    mock_rating: undefined,
    mock_is_open: true,
  },
  {
    id: 'post-3',
    author_id: 'user-demo',
    type: 'recommendation',
    title: 'Hidden gem: matcha latte at CoHo',
    description: 'The CoHo\'s oat milk matcha latte is genuinely one of the best on campus. Get the large — you\'ll need it for late night studying. The baristas are super friendly too. Pairs perfectly with the croissants.',
    image_url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=480&fit=crop',
    location_name: 'CoHo Cafe',
    latitude: 37.4255,
    longitude: -122.1710,
    cuisine_tags: ['coffee', 'boba'],
    dietary_tags: ['vegan', 'dairy-free'],
    is_free_food: false,
    circle_id: 'circle-coffee',
    created_at: new Date(NOW - 3 * HOUR).toISOString(),
    updated_at: new Date(NOW - 3 * HOUR).toISOString(),
    like_count: 89,
    still_there_count: 0,
    comment_count: 14,
    mock_rating: 4.5,
    mock_is_open: true,
  },
  {
    id: 'post-4',
    author_id: 'user-2',
    type: 'recommendation',
    title: 'EVGR late night noodle spot',
    description: 'Didn\'t know EVGR had a midnight ramen spot but here we are. The spicy tonkotsu ramen is unreal for the price. Open until 1am on weekdays. Bring cash.',
    image_url: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=480&fit=crop',
    location_name: 'EVGR',
    latitude: 37.4312,
    longitude: -122.1725,
    cuisine_tags: ['ramen', 'korean'],
    dietary_tags: [],
    is_free_food: false,
    circle_id: 'circle-late-night',
    created_at: new Date(NOW - 12 * HOUR).toISOString(),
    updated_at: new Date(NOW - 12 * HOUR).toISOString(),
    like_count: 56,
    still_there_count: 0,
    comment_count: 9,
    mock_rating: 4.2,
    mock_is_open: false,
  },
  {
    id: 'post-5',
    author_id: 'user-3',
    type: 'free_food',
    title: 'Free sandwiches after CS talk at Gates',
    description: 'Leftover catering sandwiches in the Gates lobby after the afternoon AI talk. Turkey, veggie, and BLT. Come grab one before they\'re gone!',
    image_url: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=480&fit=crop',
    location_name: 'Gates',
    latitude: 37.4300,
    longitude: -122.1733,
    cuisine_tags: ['sandwiches'],
    dietary_tags: ['vegetarian'],
    is_free_food: true,
    expires_at: new Date(NOW + 30 * 60000).toISOString(),
    circle_id: 'circle-free-food',
    created_at: new Date(NOW - 40 * 60000).toISOString(),
    updated_at: new Date(NOW - 40 * 60000).toISOString(),
    like_count: 18,
    still_there_count: 4,
    comment_count: 2,
    mock_rating: undefined,
    mock_is_open: true,
  },
  {
    id: 'post-6',
    author_id: 'user-demo',
    type: 'recommendation',
    title: 'Best matcha soft serve near campus',
    description: 'Found this tiny window spot on El Camino — only $4 for a perfect matcha soft serve. The line moves fast. They also have taro and strawberry flavors. Absolutely worth the 10-min bike ride.',
    image_url: 'https://images.unsplash.com/photo-1576506295286-5cda18df43e7?w=480&fit=crop',
    location_name: 'El Camino Real',
    latitude: 37.4228,
    longitude: -122.1663,
    cuisine_tags: ['boba', 'snacks'],
    dietary_tags: ['vegan'],
    is_free_food: false,
    circle_id: 'circle-boba',
    created_at: new Date(NOW - 6 * HOUR).toISOString(),
    updated_at: new Date(NOW - 6 * HOUR).toISOString(),
    like_count: 112,
    still_there_count: 0,
    comment_count: 22,
    mock_rating: 4.7,
    mock_is_open: true,
  },
  {
    id: 'post-7',
    author_id: 'user-3',
    type: 'event',
    title: 'Boba & Study Night @ Tresidder',
    description: 'BASES is hosting a chill boba & study night at Tresidder Student Union. Free boba, snacks, and vibes. Bring your laptop and your stress. 7–10pm tonight.',
    image_url: 'https://images.unsplash.com/photo-1534353473418-4cfa0e27ccc7?w=480&fit=crop',
    location_name: 'Tresidder',
    latitude: 37.4250,
    longitude: -122.1710,
    cuisine_tags: ['boba'],
    dietary_tags: [],
    is_free_food: true,
    expires_at: new Date(NOW + 5 * HOUR).toISOString(),
    circle_id: 'circle-boba',
    created_at: new Date(NOW - 2 * HOUR).toISOString(),
    updated_at: new Date(NOW - 2 * HOUR).toISOString(),
    like_count: 67,
    still_there_count: 0,
    comment_count: 11,
    mock_rating: undefined,
    mock_is_open: true,
  },
  {
    id: 'post-8',
    author_id: 'user-2',
    type: 'free_food',
    title: 'Study snack box outside Green Library',
    description: 'Someone left a big box of Kind bars, trail mix, and apple juice boxes near the Green Library entrance. Free for anyone — assumed it\'s for the studying crowd. Grab and go!',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=480&fit=crop',
    location_name: 'Green Library',
    latitude: 37.4265,
    longitude: -122.1672,
    cuisine_tags: ['snacks'],
    dietary_tags: ['vegan', 'gluten-free'],
    is_free_food: true,
    expires_at: new Date(NOW + 3 * HOUR).toISOString(),
    circle_id: 'circle-healthy',
    created_at: new Date(NOW - 50 * 60000).toISOString(),
    updated_at: new Date(NOW - 50 * 60000).toISOString(),
    like_count: 29,
    still_there_count: 8,
    comment_count: 5,
    mock_rating: undefined,
    mock_is_open: true,
  },
  // Off-campus Palo Alto locations
  {
    id: 'post-9',
    author_id: 'user-demo',
    type: 'recommendation',
    title: "Oren's Hummus — best Middle Eastern in Palo Alto",
    description: "If you haven't tried Oren's yet, this is your sign. The hummus is transcendent and the pita is fresh out of the oven. Perfect post-study meal. Get the chicken shawarma bowl.",
    image_url: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=480&fit=crop',
    location_name: "Oren's Hummus, Palo Alto",
    latitude: 37.4461,
    longitude: -122.1611,
    cuisine_tags: ['mediterranean', 'sandwiches'],
    dietary_tags: ['vegetarian'],
    is_free_food: false,
    circle_id: 'circle-healthy',
    created_at: new Date(NOW - 8 * HOUR).toISOString(),
    updated_at: new Date(NOW - 8 * HOUR).toISOString(),
    like_count: 73,
    still_there_count: 0,
    comment_count: 17,
    mock_rating: 4.6,
    mock_is_open: true,
  },
  {
    id: 'post-10',
    author_id: 'user-3',
    type: 'recommendation',
    title: 'Philz Coffee on Hamilton — perfect study spot',
    description: "Philz on Hamilton is legitimately the best coffee near campus. Get the Tesora or the Iced Mint Mojito. They always have outlets. Peak hours are 10am–1pm — go earlier or later to snag a seat.",
    image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=480&fit=crop',
    location_name: 'Philz Coffee, Palo Alto',
    latitude: 37.4455,
    longitude: -122.1622,
    cuisine_tags: ['coffee'],
    dietary_tags: ['vegan', 'dairy-free'],
    is_free_food: false,
    circle_id: 'circle-coffee',
    created_at: new Date(NOW - 5 * HOUR).toISOString(),
    updated_at: new Date(NOW - 5 * HOUR).toISOString(),
    like_count: 94,
    still_there_count: 0,
    comment_count: 21,
    mock_rating: 4.4,
    mock_is_open: true,
  },
  {
    id: 'post-11',
    author_id: 'user-2',
    type: 'recommendation',
    title: "Zareen's Pakistani — halal gem on El Camino",
    description: "Zareen's is an absolute hidden gem. Incredible halal Pakistani food — the chicken karahi and garlic naan will ruin you for other food. Great price for the portion size.",
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=480&fit=crop',
    location_name: "Zareen's, Mountain View",
    latitude: 37.3956,
    longitude: -122.0803,
    cuisine_tags: ['indian'],
    dietary_tags: ['halal'],
    is_free_food: false,
    created_at: new Date(NOW - 24 * HOUR).toISOString(),
    updated_at: new Date(NOW - 24 * HOUR).toISOString(),
    like_count: 58,
    still_there_count: 0,
    comment_count: 9,
    mock_rating: 4.8,
    mock_is_open: false,
  },
  {
    id: 'post-12',
    author_id: 'user-demo',
    type: 'event',
    title: 'University Ave Street Food Festival this weekend!',
    description: "Downtown Palo Alto is hosting a street food pop-up on University Ave this Saturday. 20+ food vendors, live music, free entry. Runs noon–9pm. Don't miss the Korean BBQ truck.",
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=480&fit=crop',
    location_name: 'University Ave, Palo Alto',
    latitude: 37.4429,
    longitude: -122.1600,
    cuisine_tags: ['korean', 'tacos', 'boba'],
    dietary_tags: ['vegetarian'],
    is_free_food: false,
    expires_at: new Date(NOW + 48 * HOUR).toISOString(),
    created_at: new Date(NOW - HOUR).toISOString(),
    updated_at: new Date(NOW - HOUR).toISOString(),
    like_count: 141,
    still_there_count: 0,
    comment_count: 34,
    mock_rating: undefined,
    mock_is_open: true,
  },
  {
    id: 'post-13',
    author_id: 'user-3',
    type: 'recommendation',
    title: 'Boba Guys on University Ave — worth the walk',
    description: "Boba Guys finally opened a location on University! The strawberry matcha latte is their best drink IMO. Quality is way above local shops. Bring cash — they sometimes have card issues.",
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=480&fit=crop',
    location_name: 'University Ave, Palo Alto',
    latitude: 37.4432,
    longitude: -122.1598,
    cuisine_tags: ['boba'],
    dietary_tags: ['vegan'],
    is_free_food: false,
    circle_id: 'circle-boba',
    created_at: new Date(NOW - 4 * HOUR).toISOString(),
    updated_at: new Date(NOW - 4 * HOUR).toISOString(),
    like_count: 87,
    still_there_count: 0,
    comment_count: 13,
    mock_rating: 4.3,
    mock_is_open: true,
  },
];

export const SEED_CIRCLES: FoodCircle[] = [
  {
    id: 'circle-boba',
    name: 'Boba Hunters',
    description: 'Tracking every boba spot within biking distance of campus.',
    icon_type: '🧋',
    created_at: new Date(NOW - 60 * 24 * HOUR).toISOString(),
    member_count: 248,
    is_member: false,
  },
  {
    id: 'circle-free-food',
    name: 'Free Food Alerts',
    description: 'Real-time free food sightings from events, clubs, and leftovers.',
    icon_type: '🍕',
    created_at: new Date(NOW - 90 * 24 * HOUR).toISOString(),
    member_count: 891,
    is_member: true,
  },
  {
    id: 'circle-late-night',
    name: 'Late Night Eats',
    description: 'Food that\'s actually open after midnight. Verified by night owls.',
    icon_type: '🌙',
    created_at: new Date(NOW - 45 * 24 * HOUR).toISOString(),
    member_count: 312,
    is_member: false,
  },
  {
    id: 'circle-healthy',
    name: 'Healthy / Gym Food',
    description: 'High protein, low guilt. Meals that fuel your workouts.',
    icon_type: '🥗',
    created_at: new Date(NOW - 30 * 24 * HOUR).toISOString(),
    member_count: 154,
    is_member: false,
  },
  {
    id: 'circle-coffee',
    name: 'Coffee People',
    description: 'Third-wave cafes, hidden campus espresso bars, and matcha spots.',
    icon_type: '☕',
    created_at: new Date(NOW - 20 * 24 * HOUR).toISOString(),
    member_count: 203,
    is_member: true,
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    post_id: 'post-1',
    author_id: 'user-2',
    content: 'Still here as of 10 min ago! The taro boba is so good',
    created_at: new Date(NOW - 10 * 60000).toISOString(),
  },
  {
    id: 'comment-2',
    post_id: 'post-1',
    author_id: 'user-demo',
    content: 'Just got some — confirmed! Go go go 🧋',
    created_at: new Date(NOW - 5 * 60000).toISOString(),
  },
  {
    id: 'comment-3',
    post_id: 'post-3',
    author_id: 'user-3',
    content: 'The oat milk upgrade is worth every penny',
    created_at: new Date(NOW - 2 * HOUR).toISOString(),
  },
  {
    id: 'comment-4',
    post_id: 'post-4',
    author_id: 'user-demo',
    content: 'Can confirm, bring cash. They don\'t take Apple Pay 😭',
    created_at: new Date(NOW - 8 * HOUR).toISOString(),
  },
];

export const SEED_REACTIONS: Reaction[] = [
  { id: 'r-1', post_id: 'post-1', user_id: 'user-2', type: 'like' },
  { id: 'r-2', post_id: 'post-1', user_id: 'user-3', type: 'still_there' },
  { id: 'r-3', post_id: 'post-3', user_id: 'user-2', type: 'like' },
  { id: 'r-4', post_id: 'post-4', user_id: 'user-3', type: 'like' },
];

export const SEED_MEMBERSHIPS: CircleMembership[] = [
  { circle_id: 'circle-free-food', user_id: 'user-demo', joined_at: new Date(NOW - 20 * 24 * HOUR).toISOString() },
  { circle_id: 'circle-coffee', user_id: 'user-demo', joined_at: new Date(NOW - 15 * 24 * HOUR).toISOString() },
  { circle_id: 'circle-boba', user_id: 'user-2', joined_at: new Date(NOW - 10 * 24 * HOUR).toISOString() },
  { circle_id: 'circle-late-night', user_id: 'user-3', joined_at: new Date(NOW - 5 * 24 * HOUR).toISOString() },
];
